using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.BsEnergy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.BsEnergy;

[GenerateTypedNameReferences]
public sealed partial class BsReceiverWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly string _minuteLocStr = Loc.GetString("ui-bs-energy-time-minute");
    private readonly string _hourLocStr = Loc.GetString("ui-bs-energy-time-hour");
    private readonly string _availablePowerLocStr = Loc.GetString("ui-bs-transmitter-current-supply-label");
    private readonly string _kWLocStr = Loc.GetString("ui-bs-energy-power-kvt");
    private readonly string _priceLocStr = Loc.GetString("ui-bs-receiver-price");
    private const int KvtConst = BsEnergySettings.KvtConst;
    private int _stepSize;
    private int _maxValue;
    private int _power;

    public event Action? OnWithdraw;
    public event Action<BaseButton.ButtonEventArgs>? OnEnableToggle;
    public event Action<NetEntity>? OnPressedChoiceServer;
    public event Action<int>? OnPowerRequest;

    private readonly Dictionary<NetEntity, UiElements> _currentTransmitters = new();

    private sealed class UiElements
    {
        public Button? Button;
        public RichTextLabel? GridName;
        public Label? PowerValue;
        public Label? PriceValue;
    }

    public BsReceiverWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnPressed += _ => OnWithdraw?.Invoke();
        EnableButton.OnPressed += args => OnEnableToggle?.Invoke(args);
    }

    public void SetEntity(EntityUid uid)
    {
        SpriteViewControl.SetEntity(uid);
    }

    public void UpdateUI(BsReceiverInterfaceStateMessage stateMessage)
    {
        if (_maxValue == 0 && stateMessage.MaxValue > 0)
            _maxValue = stateMessage.MaxValue;

        if (_stepSize == 0 && stateMessage.MaxValue > 0)
        {
            _stepSize = stateMessage.StepSize;
            RequestedPowerIncrease.Text = $"+{BsEnergyUtils.GetPowerText(_stepSize)}";
            RequestedPowerDecrease.Text = $"-{BsEnergyUtils.GetPowerText(_stepSize)}";

            RequestedPowerIncrease.OnPressed += _ => RequestedPowerChanged(_stepSize);
            RequestedPowerDecrease.OnPressed += _ => RequestedPowerChanged(-1 * _stepSize);
        }

        MoneyLabel.Text = $"${stateMessage.Money:F0}";
        ReceivedPowerLabel.Text = BsEnergyUtils.GetPowerText(stateMessage.ReceivedPower);
        if (stateMessage.TransmittersData.TryGetValue(stateMessage.ConnectedTransmitter, out var serversData))
        {
            var moneyLost = (float)stateMessage.ReceivedPower / KvtConst * serversData.Price;
            MoneyLost.Text = $"${moneyLost:F0} / {_minuteLocStr}";
            var minutes = (double)stateMessage.Money / moneyLost;
            if (double.IsFinite(minutes))
            {
                var time = TimeSpan.FromMinutes(minutes);
                var hours = (int)time.TotalHours;
                var hoursText = hours > 0 ? $"{hours} {_hourLocStr}. " : string.Empty;
                MoneyTime.Text = $"~{hoursText}{time.Minutes} {_minuteLocStr}";
            }
            else
            {
                MoneyTime.Text = $"{float.PositiveInfinity} {_minuteLocStr}";
            }
        }
        else
        {
            MoneyLost.Text = $"$0 / {_minuteLocStr}";
            MoneyTime.Text = $"0 {_minuteLocStr}";
        }

        UpdateServersUi(stateMessage.TransmittersData, stateMessage.Enabled);
        SelectTransmitterUi(stateMessage.ConnectedTransmitter);

        _power = stateMessage.RequestedPower;
        RequestedPowerLabel.Text = BsEnergyUtils.GetPowerText(stateMessage.RequestedPower);
        EnableButton.Pressed = stateMessage.Enabled;
    }

    private void RequestedPowerChanged(int watts)
    {
        if (_maxValue == 0)
            return;

        var newVal = _power + watts;
        _power = newVal < _maxValue ? Math.Max(0, newVal) : _maxValue;
        OnPowerRequest?.Invoke(_power);
    }

    private void UpdateServersUi(Dictionary<NetEntity, UpdateTransmitterStateData> transmittersData, bool enabled)
    {
        CheckingRemoveTransmitters(transmittersData);

        foreach (var (key, value) in transmittersData)
        {
            if (_currentTransmitters.TryGetValue(key, out var elements))
            {
                elements.Button?.Disabled = !enabled;
                elements.GridName?.Text = value.GridTransmitterName;
                elements.PowerValue?.Text = BsEnergyUtils.GetPowerText((int)value.TransmitterAvailablePower);
                elements.PriceValue?.Text = $"${value.Price:F0} / {_minuteLocStr}";
            }
            else
            {
                var mainHBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
                var gridName = new RichTextLabel { Text = $"{value.GridTransmitterName}", VerticalExpand = true, VerticalAlignment = VAlignment.Center};
                gridName.MaxWidth = 200;
                mainHBox.AddChild(gridName);

                var vBoxPower = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true, HorizontalAlignment = HAlignment.Center, Margin = new(10,0,0,0) };
                var powerText = new Label { Text = _availablePowerLocStr };
                var powerValue = new Label { Text = BsEnergyUtils.GetPowerText((int)value.TransmitterAvailablePower) };
                vBoxPower.AddChild(powerText);
                vBoxPower.AddChild(powerValue);

                mainHBox.AddChild(vBoxPower);

                var vBoxPrice = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true, HorizontalAlignment = HAlignment.Center};
                var priceText = new Label { Text = _priceLocStr };
                var priceValue = new Label { Text = $"${value.Price:F0} {_kWLocStr} / {_minuteLocStr}" };
                vBoxPrice.AddChild(priceText);
                vBoxPrice.AddChild(priceValue);

                mainHBox.AddChild(vBoxPrice);

                var btn = new Button();
                btn.AddChild(mainHBox);
                btn.Disabled = !enabled;
                btn.OnPressed += (_) =>
                {
                    OnPressedChoiceServer?.Invoke(key);
                    SelectTransmitterUi(key);
                };

                BoxInScroll.AddChild(btn);

                var newElements = new UiElements
                {
                    Button = btn,
                    GridName = gridName,
                    PowerValue = powerValue,
                    PriceValue = priceValue,
                };

                _currentTransmitters[key] = newElements;
            }
        }
    }

    private void SelectTransmitterUi(NetEntity transmitterNet)
    {
        foreach (var (_, elements) in _currentTransmitters)
        {
            elements.Button?.Modulate = Color.White;
        }

        if (!transmitterNet.IsValid())
            return;

        if (_currentTransmitters.TryGetValue(transmitterNet, out var uiElements))
            uiElements.Button?.Modulate = Color.Lime;
    }

    private void CheckingRemoveTransmitters(Dictionary<NetEntity, UpdateTransmitterStateData> newData)
    {
        var toRemove = _currentTransmitters.Keys.Where(key => !newData.ContainsKey(key)).ToList();
        foreach (var key in toRemove)
        {
            if (!_currentTransmitters.TryGetValue(key, out var elements))
                continue;

            elements.Button?.Dispose();
            _currentTransmitters.Remove(key);
        }
    }
}
