using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.BsEnergy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.BsEnergy;

[GenerateTypedNameReferences]
public sealed partial class BsTransmitterWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly string _minuteLocStr = Loc.GetString("ui-bs-energy-time-minute");
    private readonly string _balanceLocStr = Loc.GetString("ui-bs-receiver-money-label");
    private int _maxValue;
    private int _stepSize;
    private int _power;


    public event Action<int>? OnChangeTargetPower;
    public event Action<int>? OnPriceChanged;
    public event Action<BaseButton.ButtonEventArgs>? OnEnableToggle;
    public event Action? OnWithdraw;

    public BsTransmitterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Price.IsValid = val => val >= 0;
        Price.LineEditControl.PlaceHolder = $"{BsEnergySettings.PassiveIncome}";

        EnableButton.OnPressed += args => OnEnableToggle?.Invoke(args);
        WithdrawButton.OnPressed += _ => OnWithdraw?.Invoke();
        Price.ValueChanged += args => OnPriceChanged?.Invoke(args.Value);
    }

    public void SetEntity(EntityUid uid)
    {
        SpriteViewControl.SetEntity(uid);
    }

    public void UpdateUI(BsTransmitterInterfaceStateMessage stateMessage)
    {
        if (_maxValue == 0 && stateMessage.MaxValue > 0)
            _maxValue = stateMessage.MaxValue;

        if (_stepSize == 0 && stateMessage.MaxValue > 0)
        {
            _stepSize = stateMessage.StepSize;
            RequestedPowerIncrease.Text = $"+{BsEnergyUtils.GetPowerText(_stepSize)}";
            RequestedPowerDecrease.Text = $"-{BsEnergyUtils.GetPowerText(_stepSize)}";

            RequestedPowerIncrease.OnPressed += _ => RequestedPowerChanged(_stepSize);
            RequestedPowerDecrease.OnPressed += _ => RequestedPowerChanged(-1 * _stepSize);
        }

        ExpectedIncomeLabel.Text = $"${stateMessage.Income:F0} / {_minuteLocStr}";
        PowerConsumerLabel.Text = BsEnergyUtils.GetPowerText(stateMessage.PowerConsumer);
        TotalMoney.Text = $"{_balanceLocStr} ${stateMessage.Money:F0}";
        ConnectedDevicesLabel.Text = $"{stateMessage.ConnectedCount} / {stateMessage.MaxConnected}";
        _power = stateMessage.TargetPower;
        TargetPowerLabel.Text = BsEnergyUtils.GetPowerText(stateMessage.TargetPower);
        EnableButton.Pressed = stateMessage.Enabled;
        CurrentSupply.Text = BsEnergyUtils.GetPowerText(stateMessage.AvailablePower);
        DrawRate.Text = BsEnergyUtils.GetPowerText(stateMessage.DrawRate);

        if (!Price.LineEditControl.HasKeyboardFocus())
            Price.OverrideValue(stateMessage.Price);
    }

    private void RequestedPowerChanged(int watts)
    {
        if (_maxValue == 0)
            return;

        var newVal = _power + watts;
        _power = newVal < _maxValue ? Math.Max(0, newVal) : _maxValue;
        OnChangeTargetPower?.Invoke(_power);
    }
}
